services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./moto:/moto
      - /nfs/homes/almarcos/tmp/.inputrc:/root/.inputrc