services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./admin:/admin
      - ./car:/car
      - ./moto:/moto
      - ./cgi-bin:/cgi-bin/